### ISSUE TITLE
[h3d-err] Failed to compile default shaders

### ISSUE THREAD

**Issue by pmorerio** [horde3d/Horde3D#162]
Hi, 
after creating Makefiles and compiling (everything runs smoothly) I try to run the Chicago example but I get this error. I have no idea what could be wrong, every dependency and requirement looks ok. Other examples also give the same.

Thanks for your help.

```
[h3d] Initializing GL2 backend using OpenGL driver '4.5.0 NVIDIA 384.130' by 'NVIDIA Corporation' on 'GeForce GTX 960M/PCIe/SSE2'
  [h3d-warn] Render target depth precision limited to 16 bit
  [h3d-err] Failed to compile default shaders
Unable to initialize engine

```

**Comment by algts** [comment]
Hello. What branch are you using? Master or develop? 
The strange thing is that depth precision is limited to 16 bit. It seems that something is wrong with opengl initialization. Judging by the 960M graphics card, you are using a notebook, right? If it has intel card, could you try running Chicago sample on intel card? It will help in understanding whether the engine or the driver is the cause of this.

**Comment by pmorerio** [comment]
Hi, thanks for the quick reply.
I compiled from the master branch.
Yes I am using a notebook with NVIDIA graphics card.
How can I force the Chicago sample to run on my Intel card (which I have)?

**Comment by algts** [comment]
Judging from using makefiles you are using linux, right? Switching to intel card should something like this: https://www.linuxbabe.com/desktop-linux/switch-intel-nvidia-graphics-card-ubuntu
If you are on windows, just right-click on the generated executable file -> x64 -> run with graphics card -> run with integrated card (naming could be different because I don't use english as gui language, but should be something like that)

**Comment by horde3d** [comment]
At least in my Lenovo T420s you can also disable the NVIDIA card temporarily in the BIOS

**Comment by pmorerio** [comment]
Solved by updating nvidia-drivers to a newer version (430).
Thanks again for your support.
