### ISSUE TITLE
camera movement vs culling

### ISSUE THREAD

**Issue by creutzerb** [horde3d/Horde3D#199]
Hello,

I just noticed big black patches.

https://user-images.githubusercontent.com/10078731/138321582-f3ecb306-108d-4c86-be67-7e7e2e96aae3.mp4

The walls of the room are made separate tiles. When the camera turns fast enough, and with enough contrast tile/background, you can notice there are holes. I suppose they were culled one frame too many ?

**Comment by algts** [comment]
Hello. It is difficult to say at a glance. I don't know the algorithm you use to enable/disable tiles.
One thing I noticed earlier with horde is that procedurally generated meshes can have issues with culling because of the incorrect bounding box. If you are using procedural geometry check that bounding box around models/meshes is large enough.
Also, if you are using occlusion culling, horde generates occlusion queues in one frame and checks them in the next frame. So probably some meshes may not be rendered if occlusion culling is on and camera is moving very fast.

I suggest that you insert debug output in the SpatialGraph::updateQueues( uint32 filterIgnore, bool forceUpdateAllViews ) method and generate several log files with meshes currently used/culled, camera position/rotation. Maybe it can help to see some patterns of this behavior.
