### ISSUE TITLE
Endian-independent resource loading

### ISSUE THREAD

**Issue by severtsev** [horde3d/Horde3D#25]
Current loader assumes binary data endianness conforms architecture.

**Comment by thelink2012** [comment]
@zuck What's up on this? As this seems like the last thing to do before the 1.0.0 final and it's stuck for a long while now.

**Comment by zuck** [comment]
You're right, it is. There are still some issues with my PR, explained in the comments of #62.

Basically I have no time now to fix them, so any help is very welcome! The biggest problem is with array of structured data (i.e. list of 3D vertices), because in this case we can't apply a general conversion on the entire list nor on a single vertex: we have to fix them one class attribute at time...

Filling the resource loading code with all this bloating conversion code is not ideal at all, so I think we should find a better approach...I'm open to suggestions ;)

**Comment by thelink2012** [comment]
Taking a approach of something more element-oriented instead of byte-oriented should do it, that's `copy_endianless` (mirroring how `std::copy` works).

**Are the file formats endian documented?** (i.e. are they supposed to be always little or big endian)? If not that's maybe a good time to do it as it'd simplify the work massively in a level where the endianess could be detected at compile time by checking the platform (and then tested at startup if the detected endianess is correct for the sake of assurance). Then `copy_endianless` would do a bare `memcpy` (or prehaps `std::copy`) when the platform endianess conforms the file format endianess and otherwise specialized copy of each element (manually, as `std::copy` do).

Though there are platforms that allow changing endianess at runtime but I don't think it's quite common to do so outside the system programming side? But anyway if we ever see something like that in action we could just change the `copy_endinaless` to conform it.

I could give it a try and open another PR if you wish.

**Comment by zuck** [comment]
It's perfect for me, thank your for your contribution!

**Comment by zuck** [comment]
Ah, I forgot to mention that #62 works with **little endian** as reference endianess because most of Intel-based processors use this convention.

**Comment by zuck** [comment]
Fixed in bb160df3ee5dae3dfa7a5b70ea724d56f74f9764.

Thanks to @thelink2012
